from .usuario_resource import Usuario as UsuarioResource
from .usuario_resource import Usuarios as UsuariosResource
from .libro_resource import Libro as LibroResource
from .libro_resource import Libros as LibrosResource
from .prestamo_resource import Prestamo as PrestamoResource
from .prestamo_resource import Prestamos as PrestamosResource
from .notificacion_resource import Notificacion as NotificacionResource
from .notificacion_resource import Notificaciones as NotificacionesResource
from .autor_resource import Autor as AutorResource
from .autor_resource import Autores as AutoresResource
from .reseña_resource import Reseña as ReseñaResource
from .reseña_resource import Reseñas as ReseñasResource
from .guardado_resource import Guardado as GuardadoResource
from .guardado_resource import Guardados as GuardadosResource
