from .usuario import Usuario as UsuarioResource
from .usuario import Usuarios as UsuariosResource
from .libro import Libro as LibroResource
from .libro import Libros as LibrosResource
from .prestamo import Prestamo as PrestamoResource
from .prestamo import Prestamos as PrestamosResource
from .notificacion import Notificacion as NotificacionResource
from .notificacion import Notificaciones as NotificacionesResource
from .autor import Autor as AutorResource
from .autor import Autores as AutoresResource
from .reseña import Reseña as ReseñaResource
from .reseña import Reseñas as ReseñasResource
from .guardado import Guardado as GuardadoResource
from .guardado import Guardados as GuardadosResource
